<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Панель администратора</title>
</head>
<body>
<div>
    <ul>
        <li><a href="">Все заявки</a></li>
        <li><a href="">Кредиты</a></li>
        <li><a href="/clients">Клиенты</a></li>
        <li><a href="">Фотографии клиентов</a></li>
        <li><a href="">Андеррайтинг</a></li>
    </ul>
</div>
<h2>Фотографии клиентов</h2>






</body>
</html>